version: '3'
services:
  downloader:  
    build: .
    shm_size: '1gb' 
    environment:
      - TZ=Europe/Paris
      - DISPLAY_WIDTH=1600
      - DISPLAY_HEIGHT=968
    volumes:
        - /nas/Downloads:/home/OrigDir
        - /nas/Videos/Series:/home/DestDir
        - /app/docker/data/Downloader/config:/home/config
        - /app/docker/data/Downloader/chrome:/root/.config/chromium/
    ports:
      - 8070:8080
